/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: AG3D _-=-_ Follow me in Instagram: ag3d_design (https://sketchfab.com/gordillo.antonio.j)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/meetmat2-astronauta-7e89bb24808d4cf484e413ed4767c9b2
Title: #MeetMAT2 astronauta
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.blinn4SG} />
          <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials.MeetMat2_defaultMat} />
          <mesh geometry={nodes.defaultMaterial_14.geometry} material={materials.blinn2SG} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
